import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import Settings from "@/components/Settings";
import Navigation from "@/components/Navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/images/favicon.ico" sizes="any" />
      </head>
      <body className={inter.className}>
        <Settings />
        <div className="flex h-woSettings">
          <Navigation />
          <main className="flex-1 overflow-y-scroll p-5">{children}</main>
        </div>
      </body>
    </html>
  );
}
