import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import Settings from "@/components/Settings";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/images/favicon.ico" sizes="any" />
      </head>
      <body className={inter.className}>
        <Settings />
        {children}
      </body>
    </html>
  );
}
