import { BlogFrontMatter } from "@/types";

type LinkedPostsType = Omit<BlogFrontMatter, "slug"> & { link: string };

export const linkedPosts: LinkedPostsType[] = [
  {
    link: "https://hwanheejung.tistory.com/61",
    title: "Socket",
    description: "",
    date: "2024-9-6",
    categoryId: 2.1,
  },
  {
    link: "https://hwanheejung.tistory.com/60",
    title: "How Polabo Optimizes Image",
    description: "",
    date: "2024-8-28",
    categoryId: 1.2,
  },
  {
    link: "https://hwanheejung.tistory.com/57",
    title: "Module System",
    description: "",
    date: "2024-8-20",
    categoryId: 3,
  },
  {
    link: "https://hwanheejung.tistory.com/36",
    title: "Network Layer (L3)",
    description: "",
    date: "2024-8-19",
    categoryId: 2.1,
  },
  {
    link: "https://hwanheejung.tistory.com/52",
    title: "Sorting Algorithm",
    description: "Performance comparison and situational selection criteria",
    date: "2024-8-7",
    categoryId: 2.2,
  },
  {
    link: "https://hwanheejung.tistory.com/51",
    title: "Recovering Abnormal Closure Strategy",
    description: "",
    date: "2024-7-31",
    categoryId: 1.1,
  },
  {
    link: "https://hwanheejung.tistory.com/48",
    title: "N:N Video Conference, OpenVidu",
    description: "",
    date: "2024-7-21",
    categoryId: 1.1,
  },
  {
    link: "https://hwanheejung.tistory.com/50",
    title: "[Next.js] Data Mutation: Server Actions",
    description: "",
    date: "2024-7-16",
    categoryId: 3,
  },
  {
    link: "https://hwanheejung.tistory.com/47",
    title: "1:1 Video Conference",
    description: "",
    date: "2024-7-5",
    categoryId: 1.1,
  },
  {
    link: "https://hwanheejung.tistory.com/46",
    title: "Starting Discord Clone Project",
    description: "",
    date: "2024-7-2",
    categoryId: 1.1,
  },
  {
    link: "https://hwanheejung.tistory.com/44",
    title: "CSS Responsive Design",
    description: "",
    date: "2024-6-26",
    categoryId: 3,
  },
  {
    link: "https://hwanheejung.tistory.com/42",
    title: "WebSocket+STOMP",
    description: "",
    date: "2024-5-29",
    categoryId: 1.1,
  },
  {
    link: "https://hwanheejung.tistory.com/39",
    title: "Web Socket",
    description: "",
    date: "2024-5-24",
    categoryId: 1.1,
  },
  {
    link: "https://hwanheejung.tistory.com/37",
    title: "Hash Table",
    description: "",
    date: "2024-5-9",
    categoryId: 2.2,
  },
  {
    link: "https://hwanheejung.tistory.com/35",
    title: "Create a Queue with 2 Stacks, Create a Stack with 2 Queues",
    description: "",
    date: "2024-5-7",
    categoryId: 2.2,
  },
  {
    link: "https://hwanheejung.tistory.com/33",
    title: "Physical Layer(L1), Data Link Layer(L2)",
    description: "",
    date: "2024-5-6",
    categoryId: 2.1,
  },
  {
    link: "https://hwanheejung.tistory.com/32",
    title: "Network",
    description: "",
    date: "2024-5-4",
    categoryId: 2.1,
  },
  {
    link: "https://hwanheejung.tistory.com/27",
    title: "TSC: How TypeScript turns into JavaScript",
    description: "",
    date: "2024-4-30",
    categoryId: 3,
  },
  {
    link: "https://hwanheejung.tistory.com/24",
    title: "Use TypeScript 100%",
    description: "",
    date: "2024-4-12",
    categoryId: 3,
  },
  {
    link: "https://hwanheejung.tistory.com/23",
    title: "React Optimization",
    description: "",
    date: "2024-4-11",
    categoryId: 3,
  },
  {
    link: "https://hwanheejung.tistory.com/22",
    title: "React: Immutable Data Pattern",
    description: "",
    date: "2024-4-11",
    categoryId: 3,
  },
  {
    link: "https://hwanheejung.tistory.com/19",
    title: "How JavaScript Handle Async",
    description: "",
    date: "2024-4-5",
    categoryId: 3,
  },
  {
    link: "https://hwanheejung.tistory.com/18",
    title: "Why Use React?",
    description: "",
    date: "2024-4-4",
    categoryId: 3,
  },
  {
    link: "https://hwanheejung.tistory.com/15",
    title: "JWT Strategy",
    description: "",
    date: "2024-3-28",
    categoryId: 1.3,
  },
  {
    link: "https://hwanheejung.tistory.com/13",
    title: "Atomic Design Pattern",
    description: "",
    date: "2024-3-27",
    categoryId: 1.3,
  },
  {
    link: "https://hwanheejung.tistory.com/11",
    title: "Pirogramming Website Renewal",
    description: "",
    date: "2024-3-26",
    categoryId: 3,
  },
];
